vpc:
  dev:
    subnets:
      - subnet-5aa2b22c
    security_groups:
      - sg-0da7caf7113fd6f4f
      - sg-03abda73886b474d0

region: us-east-1
traffic_percentage: 100
duration_minutes: 5

functions:
  - name: Payment-Session-HelloT
    repo_url: "https://github.com/navneetkashyap-webners/wbs.git"
    repo_branch: "development"
    path: test/publish0/
    CodeUri: test/publish0/
    handler: HelloWorldLambda::HelloWorldLambda.Function::FunctionHandler
    memory: 512
    timeout: 30
    environment:
      Environment: development
      QueueName: Dev-TranzPay-SendSMS-Queue
      URL: https://notify.tranzpaydev.com/sms/send
    triggers:
      - type: s3
        arn: arn:aws:s3:::notifications-sftp-dev

