vpc:
  prod:
    subnets:
      - subnet-0d929a68ce19ad1c7
    security_groups:
      - sg-029668d231d090f15
      - sg-0963ffae6c806ae69

region: us-east-1
traffic_percentage: 100
duration_minutes: 5

functions:
  - name: Payment-Session-Hello
    handler: notification-DeliveryReport::notification.DeliveryReport.Function::FunctionHandler
    memory: 512
    timeout: 30
    environment:
      Environment: production
      QueueName: Dev-TranzPay-SendSMS-Queue
      URL: https://notify.tranzpay.com/sms/send





