vpc:
  dev:
    subnets: subnet-5aa2b22c
    security_groups: sg-0759b55b0464beb0a
  prod:
    subnets: subnet-0d929a68ce19ad1c7
    security_groups: sg-029668d231d090f15

region: us-east-1
traffic_percentage: 100
duration_minutes: 5

functions:
  - name: Payment-Session-Dev
    handler: notification-SFTPProcessor::TranzPay.Notification.SFTPProcessor.SFTPProcessorLambda::FunctionHandler
    environment:
      Environment: development
      QueueName: Dev-TranzPay-SendSMS-Queue
      URL: https://notify.tranzpaydev.com/sms/send
    triggers:
      - type: s3
        bucket: notifications-sftp-dev

