lambda_function: Payment-Session-Navneet
environment: dev
traffic_percentage: 10
duration_minutes: 5
region: us-east-1
project_path: ./src/lambdas
framework: net8.0
configuration: Release


