vpc:
  dev:
    subnets:
      - subnet-5aa2b22c
    security_groups:
      - sg-0da7caf7113fd6f4f

region: us-east-1
traffic_percentage: 100
duration_minutes: 5

functions:
  - name: Payment-Session-HelloTest
    path: trial/
    handler: notification-SFTPProcessor::TranzPay.Notification.SFTPProcessor.SFTPProcessorLambda::FunctionHandler
    memory: 512
    timeout: 30
    environment:
      Environment: development
      QueueName: Dev-TranzPay-SendSMS-Queue
      URL: https://notify.tranzpaydev.com/sms/send
    triggers:
      - type: s3
        arn: arn:aws:s3:::notifications-sftp-dev



