lambda_function: Payment-Session-HelloTest
environment: dev
traffic_percentage: 100
duration_minutes: 4
region: us-east-1
project_path: ./
framework: net8.0
configuration: Release
Git_repo: https://github.com/navneetkashyap-webners/wbs.git


