name: Deploy .NET Lambda

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
    
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Install AWS CLI, yq, jq
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip jq
          curl -s https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip -o awscliv2.zip
          unzip -q awscliv2.zip
          sudo ./aws/install --update
          sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq
          sudo chmod +x /usr/bin/yq

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Update to match config.yml
      
      - name: Download deploy scripts from S3
        run: aws s3 cp s3://autodeploy-scripts/ ./ --recursive

      - name: Make scripts executable
        run: chmod +x *.sh

      - name: Build .NET Lambda project
        run: |
          dotnet restore
          dotnet publish -c Release -o ./publish

      - name: Zip Lambda package
        run: |
          cd publish
          zip -r ../lambda_package.zip . > /dev/null
          cd ..
      - name: Deploy Lambda
        run: ./deploy_lambda.sh
