name: Trigger Deploy Workflow

on:
  push:
    branches:
      - development
      - master

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch to master workflow
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          event-type: deploy
          client-payload: >-
            {
              "ref": "${{ github.ref_name }}",
              "event_name": "${{ github.event_name }}",
              "actor": "${{ github.actor }}",
              "sha": "${{ github.sha }}"
            }
